extends: airbnb-base

parser: babel-eslint
parserOptions:
  ecmaVersion: 2017

env:
  browser: true

rules:
  semi: [error, never]
  eqeqeq: [error, smart]
  no-empty: 0
  no-console: 0
  no-empty-pattern: 0
  no-param-reassign: [error, { props: false }]
  no-plusplus: [error, { allowForLoopAfterthoughts: true }]
  import/extensions: always
